### ISSUE TITLE
Возможность получения вложений

### ISSUE THREAD

**Issue by xzfantom** [dmpas/oscript-mail#10]
При попытке получения количества вложений возвращает 0 даже если они есть.
Я так понимаю, данная возможность не реализована. Если это так, то есть ли такое в планах?

**Comment by dmpas** [comment]
В планах пока не было. Руки дойдут - запилим обязательно.

**Comment by xzfantom** [comment]
Добавил код:

https://github.com/xzfantom/oscript-mail/commit/290950c0be2f30b549e905d1ddca30ef71104462

Я не .netчик, поэтому не уверен в его полной корректности, но вложения сохраняет) 
Для моих задач пока хватит, если всё не так плохо, может добавите в основную ветку?

**Comment by dmpas** [comment]
@xzfantom спасибо, обязательно посмотрю!
