### ISSUE TITLE
Ошибка добавления получателя

### ISSUE THREAD

**Issue by a-grinyuk** [dmpas/oscript-mail#17]
Собственно ошибка видна на скриншоте. Подскажите почему такое может происходить?

![default](https://user-images.githubusercontent.com/35609057/43090570-f1b671d2-8ed1-11e8-90a6-3413aef0577e.png)

**Comment by dmpas** [comment]
@a-grinyuk версии движка и библиотеки? У меня работает... InternetMail@1.0.4 и OneScript@1.0.20.108

**Comment by a-grinyuk** [comment]
OneScript@1.0.20.108 (х32)
InternetMail@1.0.5
1С:Предприятие 8.3.12.1412 (х64)

**Comment by dmpas** [comment]
@a-grinyuk в `1.0.5` действительно не работает. Пока исправляю, можно попробовать пользоваться `1.0.4`.

**Comment by dmpas** [comment]
@a-grinyuk попробуйте https://ci.appveyor.com/api/buildjobs/gcqona88ackqnw7t/artifacts/InternetMail-1.0.6.ospx

**Comment by ViktorErmakov** [comment]
Сергей, вот с установленной библиотекой по ссылке выше, почта стала работать, но опять таки на строке добавления получателя, если идти отладчиком, то он после шага выполняет код без отладки.
Надеюсь понятно объяснил)) Картинка:
![image](https://user-images.githubusercontent.com/39617680/51984047-60969680-24ab-11e9-8d5a-1b302258e904.png)
