### ISSUE TITLE
Метод не обнаружен ПочтовоеСообщение.Тексты.Добавить()

### ISSUE THREAD

**Issue by fast8-saim** [dmpas/oscript-mail#19]
Ошибка в строке: 11 / Метод объекта не обнаружен (Добавить)}    
		ПочтовоеСообщение.Тексты.Добавить("Скрипт работает. Привет, Мир");

{Модуль E:\8_ONESCRIPT\post-test.os / Ошибка в строке: 11 / Внешнее исключение (System.MissingMethodException): Метод не найден: "Void ScriptEngine.Machine.Contexts.ContextMethodAttribute..ctor(System.String, System.String, Boolean, Boolean)".}

OneScript@1.0.21 (х32)
InternetMail@1.0.5

**Comment by dmpas** [comment]
Дубль с #17 
1.0.4 работает, остальные надо пересобрать, но звёзды не сойдутся....

**Comment by fast8-saim** [comment]
1.0.4:

{Модуль E:\8_ONESCRIPT\post-test.os / Ошибка в строке: 12 / Значение не является значением объектного типа}    
ПочтовоеСообщение.Отправитель.Адрес = "zzz@yandex.ru";

{Модуль E:\8_ONESCRIPT\post-test.os / Ошибка в строке: 16 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.}    
ИнтернетПочта.Послать(ПочтовоеСообщение);


#Использовать InternetMail 
Профиль = Новый ИнтернетПочтовыйПрофиль;
//Профиль.АутентификацияSMTP	= СпособSMTPАутентификации.Login;
Профиль.АдресСервераSMTP	= "smtp.yandex.ru";
Профиль.ПортSMTP			= 465;
Профиль.ПользовательSMTP	= "xxx@yandex.ru";
Профиль.ПарольSMTP			= "yyy";
Профиль.ИспользоватьSSLSMTP = Истина; 
ПочтовоеСообщение = Новый ИнтернетПочтовоеСообщение;
ПочтовоеСообщение.Тема = "Диагностика скрипта";
ПочтовоеСообщение.Тексты.Добавить("Скрипт работает. Привет, Мир");
ПочтовоеСообщение.Отправитель.Адрес = "zzz@yandex.ru";
ПочтовоеСообщение.Получатели.Добавить("qqq@yandex.ru");
ИнтернетПочта = Новый ИнтернетПочта;
ИнтернетПочта.Подключиться(Профиль);
ИнтернетПочта.Послать(ПочтовоеСообщение);
ИнтернетПочта.Отключиться();

**Comment by mrOwner** [comment]
Присоединяюсь к проблеме.
Такая же ошибка на версии 1.0.5
На версии 1.0.4:

```
Профиль = Новый ИнтернетПочтовыйПрофиль;
	
Профиль.АдресСервераSMTP    				= "10.10.10.10";
Профиль.ИспользоватьSSLSMTP					= Истина;
Профиль.ПарольSMTP 							= "password";
Профиль.ПользовательSMTP 					 = "send";
Профиль.ПортSMTP 							= 465;
Профиль.Таймаут								= 30;
Профиль.ТолькоЗащищеннаяАутентификацияSMTP	= Ложь;
	
Письмо = Новый ИнтернетПочтовоеСообщение;
Письмо.ОбратныйАдрес.Добавить("send@company.ru");
Письмо.Получатели.Добавить("user@company.ru");
	
Письмо.Отправитель = "send@company.ru";
Письмо.Тема        = Тема;
Текст =  "
|<h3>"+Текст+"</h3>";
	
Почта = Новый ИнтернетПочта;
Почта.Подключиться(Профиль);
Почта.Послать(Письмо, , ПротоколИнтернетПочты.SMTP);
Почта.Отключиться();
```
/ Внешнее исключение (System.IO.IOException): Сбой установки соединения из-за неожиданного формата пакета.}

На строке Подключиться()

**Comment by dmpas** [comment]
@fast8-saim @mrOwner попробуйте 
https://ci.appveyor.com/api/buildjobs/gcqona88ackqnw7t/artifacts/InternetMail-1.0.6.ospx

**Comment by tomskih13** [comment]
Добрый день,
присоединяюсь к проблеме.

C:\Users\Программист>oscript
1Script Execution Engine. Version 1.0.21.1


ЛогинИнтернетПочты 		=   "mail@yandex.ru";
ПарольИнтернетПочты   	=   "888"; 
			
Профиль = Новый ИнтернетПочтовыйПрофиль;
Профиль.АдресСервераSMTP  	=	"smtp.ya.ru";
Профиль.ПользовательSMTP  	=	ЛогинИнтернетПочты;
Профиль.ПарольSMTP			=	ПарольИнтернетПочты;
Профиль.ПортSMTP			=	465;
Профиль.ИспользоватьSSLSMTP	=	Истина;
							
ИнтернетПочтовоеСообщение = Новый ИнтернетПочтовоеСообщение; 

ИнтернетПочтовоеСообщение.Отправитель	=	ЛогинИнтернетПочты;
ИнтернетПочтовоеСообщение.ОбратныйАдрес.Добавить(ЛогинИнтернетПочты);
ИнтернетПочтовоеСообщение.СписокПочтовыхПолучателей.Добавить("mail.mail.ru");
			
ИнтернетПочтовоеСообщение.Тексты.Добавить(ТекстСообщения);
			
Почта	=	Новый ИнтернетПочта;
Попытка
	Почта.Подключиться(Профиль);
	Почта.Послать(ИнтернетПочтовоеСообщение,,ПротоколИнтернетПочты.SMTP);
	Почта.Отключиться();
	Сообщить("Сообщение отправлено!");
Исключение
	Сообщить(ОписаниеОшибки());
КонецПопытки;


Падение на строке :
             ИнтернетПочтовоеСообщение.Отправитель	=	ЛогинИнтернетПочты;
(или любого другого обращения к к реквизитам ИнтернетПочтовоеСообщение)
с ошибкой:
{Модуль C:\oscript\Проверка места / Ошибка в строке: 65 / Внешнее исключение (System.MissingMethodException): Метод не найден: "Void ScriptEngine.Machine.Contexts.ContextMethodAttribute..ctor(System.String, System.String, Boolean, Boolean)".}


я новичок в oscript.
что делать с ospx не смог разобраться

**Comment by dmpas** [comment]
@tomskih13 скачать, потом в консоли под админом сделать
`opm install -f InternetMail-1.0.6.ospx`

**Comment by tomskih13** [comment]
Огромное спасибо! при запуске через debug все сработало.

делаю oscript -make "C:\oscript\Проверка места" "Проверка места.exe"

запускаю полученный exe

получаю ошибку:

{Модуль Проверка места.exe:$entry / Ошибка в строке: 49 / Конструктор не найден (ИнтернетПочтовыйПрофиль)}

может необходимо какую-то библиотеку подложить? куда?

**Comment by nixel2007** [comment]
Сборка библиотек с dll в exe на текущий момент не поддерживается движком OneScript

**Comment by tomskih13** [comment]
Понял. спасибо
