### ISSUE TITLE
Установка имя отправителя в сообщении

### ISSUE THREAD

**Issue by KvestIn** [dmpas/oscript-mail#3]
При отправке не удается установить имя отправителя в сообщении.
Т.е. необходимо, чтобы светился не просто e-mail, а какое-то имя.
Пробовал:
```
Сообщение = Новый ИнтернетПочтовоеСообщение;
....
Сообщение.Отправитель = "test@test.ru";
Сообщение.ИмяОтправителя = "Test";
```
Отправляет, но имени нет.
Так:
```
Сообщение.Отправитель = "Test <test@test.ru>";
```
Вообще не отправляет:
```
 Внешнее исключение (MailKit.Net.Smtp.SmtpCommandException): 5.1.7 Bad address mailbox s
yntax.}```

**Comment by dmpas** [comment]
А в 1С оба варианта срабатывают?

**Comment by KvestIn** [comment]
Хороший вопрос. Я не 1С код портировал, а с "0" на оскрипте писал. Могу проверить, если надо.

**Comment by KvestIn** [comment]
На 1С поле Отправитель может быть либо строкой (только адрес) либо ИнтернетПочтовыйАдрес, в котором уже задается адрес и отображаемое имя.
Вариант ```Сообщение.Отправитель = "Test <test@test.ru>";``` - не работает.
```Сообщение.ИмяОтправителя = "Test";``` - работает.
В БСП так:
```
Письмо.ИмяОтправителя              = РеквизитыОтправителя.ИмяПользователя;
Письмо.Отправитель.ОтображаемоеИмя = РеквизитыОтправителя.ИмяПользователя;
Письмо.Отправитель.Адрес           = РеквизитыОтправителя.АдресЭлектроннойПочты;
```
